__title__ = "gitflic"
__version__ = "0.11"
__description__ = "GitflicApi wrapper"
__author__ = "SantaSpeen"
__author_email__ = "dir@sssr.dev"
__url__ = "https://github.com/SantaSpeen/gitflic"
__license__ = "Apache License 2.0 "
